//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrossoutLogView.GUI.LocalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LogResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LogResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CrossoutLogView.GUI.LocalResources.LogResources", typeof(LogResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initialize Session..
        /// </summary>
        internal static string AppInit {
            get {
                return ResourceManager.GetString("AppInit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session initialized..
        /// </summary>
        internal static string AppInitD {
            get {
                return ResourceManager.GetString("AppInitD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigating content. Type:.
        /// </summary>
        internal static string Navi_NavigateTo {
            get {
                return ResourceManager.GetString("Navi_NavigateTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply theme changes..
        /// </summary>
        internal static string Sett_ChangeTheme {
            get {
                return ResourceManager.GetString("Sett_ChangeTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading component ViewModel..
        /// </summary>
        internal static string ViewModelInit {
            get {
                return ResourceManager.GetString("ViewModelInit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ViewModel loaded..
        /// </summary>
        internal static string ViewModelInitD {
            get {
                return ResourceManager.GetString("ViewModelInitD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading Window..
        /// </summary>
        internal static string WinInit {
            get {
                return ResourceManager.GetString("WinInit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initialized Component..
        /// </summary>
        internal static string WinInitD {
            get {
                return ResourceManager.GetString("WinInitD", resourceCulture);
            }
        }
    }
}
