//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrossoutLogView.GUI.LocalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class WindowResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WindowResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CrossoutLogView.GUI.LocalResources.WindowResources", typeof(WindowResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading Live Tracking.
        /// </summary>
        internal static string Live_LoadingHeader {
            get {
                return ResourceManager.GetString("Live_LoadingHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait..
        /// </summary>
        internal static string Live_LoadingMessage {
            get {
                return ResourceManager.GetString("Live_LoadingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corssout Log VIewer: Live Tracking.
        /// </summary>
        internal static string Live_Title {
            get {
                return ResourceManager.GetString("Live_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading Application.
        /// </summary>
        internal static string Lnch_LoadingHeader {
            get {
                return ResourceManager.GetString("Lnch_LoadingHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing datastructure, collecting logs, evaluating statistics.
        ///Please stand by..
        /// </summary>
        internal static string Lnch_LoadingMessage {
            get {
                return ResourceManager.GetString("Lnch_LoadingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corssout Log VIewer: Launcher.
        /// </summary>
        internal static string Lnch_Title {
            get {
                return ResourceManager.GetString("Lnch_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete database confirmation.
        /// </summary>
        internal static string Sett_DelDB_Header {
            get {
                return ResourceManager.GetString("Sett_DelDB_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting the database can result in a loss of data because Crossout deletes thier logs after a certain period of time.
        ///Are you sure that you which to proceed?.
        /// </summary>
        internal static string Sett_DelDB_Message {
            get {
                return ResourceManager.GetString("Sett_DelDB_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading Collected Statistics.
        /// </summary>
        internal static string Stat_LoadingHeader {
            get {
                return ResourceManager.GetString("Stat_LoadingHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait..
        /// </summary>
        internal static string Stat_LoadingMessage {
            get {
                return ResourceManager.GetString("Stat_LoadingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Games.
        /// </summary>
        internal static string Stat_NavGames {
            get {
                return ResourceManager.GetString("Stat_NavGames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maps.
        /// </summary>
        internal static string Stat_NavMaps {
            get {
                return ResourceManager.GetString("Stat_NavMaps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        internal static string Stat_NavUsers {
            get {
                return ResourceManager.GetString("Stat_NavUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weapons.
        /// </summary>
        internal static string Stat_NavWeapons {
            get {
                return ResourceManager.GetString("Stat_NavWeapons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Stat_PageSettings {
            get {
                return ResourceManager.GetString("Stat_PageSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crossout Log Viewer: Collected Statistics.
        /// </summary>
        internal static string Stat_Title {
            get {
                return ResourceManager.GetString("Stat_Title", resourceCulture);
            }
        }
    }
}
